run:
  timeout: 5m
  tests: true

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - unused
    - gosimple
    - ineffassign
    - typecheck

output:
  formats:
    - format: colored-line-number

linters-settings:
  errcheck:
    check-type-assertions: false
    check-blank: false

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
  max-issues-per-linter: 50
  max-same-issues: 10
