# GoReleaser configuration for Synth.
# https://goreleaser.com

version: 2

before:
  hooks:
    - go mod tidy

builds:
  - main: ./cmd/synth
    binary: synth
    env:
      - CGO_ENABLED=1
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
    flags:
      - -trimpath

archives:
  - format: tar.gz
    name_template: "synth_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: 'sha256sums.txt'

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
